# permissions for end users to view bikes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bike-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ice-operator
    app.kubernetes.io/part-of: ice-operator
    app.kubernetes.io/managed-by: kustomize
  name: bike-viewer-role
rules:
- apiGroups:
  - webapp.my.domain
  resources:
  - bikes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.my.domain
  resources:
  - bikes/status
  verbs:
  - get
