# permissions for end users to edit rulebooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: rulebook-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ice-operator
    app.kubernetes.io/part-of: ice-operator
    app.kubernetes.io/managed-by: kustomize
  name: rulebook-editor-role
rules:
- apiGroups:
  - webapp.my.domain
  resources:
  - rulebooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.my.domain
  resources:
  - rulebooks/status
  verbs:
  - get
