---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - jjeaby.github.com
  resources:
  - jellybeanzs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jjeaby.github.com
  resources:
  - jellybeanzs/finalizers
  verbs:
  - update
- apiGroups:
  - jjeaby.github.com
  resources:
  - jellybeanzs/status
  verbs:
  - get
  - patch
  - update
